import topoSiteUrl from "@/assets/topo-site.jpg";
import bannerFalsaCentralUrl from "@/assets/banner-golpe.jpg";
import caixaLoginUrl from "@/assets/caixa-login.png";
import botaoAvancarUrl from "@/assets/botao-avancar.png";
import botaoCancelarUrl from "@/assets/botao-cancelar-acesso.png";
import colunaGolpesUrl from "@/assets/coluna-golpes.png";
import rodapeUrl from "@/assets/rodape.png";
import caixaLoaderUrl from "@/assets/caixa-loader.png";
import caixaTokenUrl from "@/assets/caixa-token.jpg";
import biaImgUrl from "@/assets/bia.png";
import fundoBiaUrl from "@/assets/img-passo-11.png";
import biaLogoUrl from "@/assets/bia-logo.png";
import iconeTokenCelularUrl from "@/assets/icone-token-celular.png";
import iconeTokenChaveiroUrl from "@/assets/icone-token-chaveiro.png";

export const topoSite = { url: topoSiteUrl };
export const bannerFalsaCentral = { url: bannerFalsaCentralUrl };
export const caixaLogin = { url: caixaLoginUrl };
export const botaoAvancar = { url: botaoAvancarUrl };
export const botaoCancelar = { url: botaoCancelarUrl };
export const colunaGolpes = { url: colunaGolpesUrl };
export const rodape = { url: rodapeUrl };
export const caixaLoader = { url: caixaLoaderUrl };
export const caixaToken = { url: caixaTokenUrl };
export const biaImg = { url: biaImgUrl };
export const fundoBia = { url: fundoBiaUrl };
export const biaLogo = { url: biaLogoUrl };
export const iconeTokenCelular = { url: iconeTokenCelularUrl };
export const iconeTokenChaveiro = { url: iconeTokenChaveiroUrl };
