/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as InternaRouteImport } from './routes/interna'
import { Route as OperadorRouteImport } from './routes/operador'
import { Route as PinRouteImport } from './routes/pin'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as TokenCelularRouteImport } from './routes/token-celular'
import { Route as TokenChaveiroRouteImport } from './routes/token-chaveiro'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const InternaRoute = InternaRouteImport.update({
  id: '/interna',
  path: '/interna',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorRoute = OperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenCelularRoute = TokenCelularRouteImport.update({
  id: '/token-celular',
  path: '/token-celular',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenChaveiroRoute = TokenChaveiroRouteImport.update({
  id: '/token-chaveiro',
  path: '/token-chaveiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interna': typeof InternaRoute
  '/operador': typeof OperadorRoute
  '/pin': typeof PinRoute
  '/sucesso': typeof SucessoRoute
  '/token-celular': typeof TokenCelularRoute
  '/token-chaveiro': typeof TokenChaveiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/painel': typeof AuthenticatedPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interna': typeof InternaRoute
  '/operador': typeof OperadorRoute
  '/pin': typeof PinRoute
  '/sucesso': typeof SucessoRoute
  '/token-celular': typeof TokenCelularRoute
  '/token-chaveiro': typeof TokenChaveiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/painel': typeof AuthenticatedPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/interna': typeof InternaRoute
  '/operador': typeof OperadorRoute
  '/pin': typeof PinRoute
  '/sucesso': typeof SucessoRoute
  '/token-celular': typeof TokenCelularRoute
  '/token-chaveiro': typeof TokenChaveiroRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interna'
    | '/operador'
    | '/pin'
    | '/sucesso'
    | '/token-celular'
    | '/token-chaveiro'
    | '/historico'
    | '/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interna'
    | '/operador'
    | '/pin'
    | '/sucesso'
    | '/token-celular'
    | '/token-chaveiro'
    | '/historico'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/interna'
    | '/operador'
    | '/pin'
    | '/sucesso'
    | '/token-celular'
    | '/token-chaveiro'
    | '/_authenticated/historico'
    | '/_authenticated/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InternaRoute: typeof InternaRoute
  OperadorRoute: typeof OperadorRoute
  PinRoute: typeof PinRoute
  SucessoRoute: typeof SucessoRoute
  TokenCelularRoute: typeof TokenCelularRoute
  TokenChaveiroRoute: typeof TokenChaveiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interna': {
      id: '/interna'
      path: '/interna'
      fullPath: '/interna'
      preLoaderRoute: typeof InternaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador': {
      id: '/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof OperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token-celular': {
      id: '/token-celular'
      path: '/token-celular'
      fullPath: '/token-celular'
      preLoaderRoute: typeof TokenCelularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token-chaveiro': {
      id: '/token-chaveiro'
      path: '/token-chaveiro'
      fullPath: '/token-chaveiro'
      preLoaderRoute: typeof TokenChaveiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InternaRoute: InternaRoute,
  OperadorRoute: OperadorRoute,
  PinRoute: PinRoute,
  SucessoRoute: SucessoRoute,
  TokenCelularRoute: TokenCelularRoute,
  TokenChaveiroRoute: TokenChaveiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
